dist: trusty

sudo: required

language: python

os:
  - linux

python:
  - '3.6'

install: pip install -U pip 

before_deploy:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker pull python:3-slim

deploy:
  provider: script
  script: bash build.sh
  on:
    branch: master
